### ISSUE TITLE
HSQL library hodgepodge

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/uPortal-start#119]
When using an _older_ version of uPortal (i.e. uPortalVersion=5.0.5) because _milestone_, the HSQL libs could be in a state where there are two versions.

```
$ find -name 'hsql*.jar'
./.gradle/tomcat/webapps/uPortal/WEB-INF/lib/hsqldb-2.3.2.jar
./.gradle/tomcat/webapps/uPortal/WEB-INF/lib/hsqldb-2.4.0.jar
```

This results in data import/init errors and HsqlExceptions like the following (if one happens to be running HSQL in the foreground)
```
org.hsqldb.HsqlException: HSQLDB server version is '2.4.0'  client version '2.1.0.0' is not compatible.
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.server.ServerConnection.init(Unknown Source)
	at org.hsqldb.server.ServerConnection.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce

1. Clone uPortal-start
2. ```./gradlew portalInit```
3. Update gradle.properties such that uPortalVersion=5.0.5
4. ```./gradlew clean tomcatClean portalInit```

**Comment by ChristianMurphy** [comment]
Hey @jonathanmtran,
uPortal start is currently transitioning to uPortal 5.1.0.
Part of that is an HSQL upgrade. https://github.com/Jasig/uPortal-start/pull/101
To run uPortal-start with uPortal 5.0.5 use the rel-5-0-patches branch.
https://github.com/Jasig/uPortal-start/tree/rel-5-0-patches

**Comment by drewwills** [comment]
Thanks very much for creating this ticket!  I was about to create one, until I discovered we already had one.

**Comment by drewwills** [comment]
Merged.
