### ISSUE TITLE
Turn off Wiki feature for this uPortal-start repo

### ISSUE THREAD

**Issue by apetro** [Jasig/uPortal-start#13]
I hope we're not going to use the GitHub Wiki feature, instead more virtuously using a docs directory so that documentation can be versioned with the software it documents.

But if we are going to use that Wiki, I hope we're going to do so intentionally and thoughtfully.

Turn off the Wiki feature until and unless we're ready to use it intentionally and thoughtfully.

**Comment by ChristianMurphy** [comment]
SGTM

**Comment by apetro** [comment]
(Done).
