### ISSUE TITLE
Turn off Projects feature for uPortal-start repo

### ISSUE THREAD

**Issue by apetro** [Jasig/uPortal-start#14]
I don't think we're ready to use the GitHub Projects feature with this repository. We may well find opportunities to use that feature in the future, but we're not using it right now, so right now it's adding more UI noise than it is adding value.  Turn it off until it needs to be turned on.

**Comment by ChristianMurphy** [comment]
SGTM for now.
In the future if uPortal migrates to GitHub issues, projects could be a good way to represent epics/major efforts.

**Comment by apetro** [comment]
(Done.)
