### ISSUE TITLE
Remove from task dataImport the dependency overlays:uPortal:compileLess

### ISSUE THREAD

**Issue by jgribonvald** [Jasig/uPortal-start#213]
**Is your feature request related to a problem? Please describe.**

Each time running dataImport task it run the compileLess task as dependency (maybe from prepareSkin task), whereas it's totaly useless

**Describe the solution you'd like**
remove from dependency task the compileLess task

**Comment by ChristianMurphy** [comment]
Resolved in #227

**Comment by jgribonvald** [comment]
Mhhh I've just seen (sorry i stayed on the longest task for me) it run also tomcatDeploy is it normal ? I think it's dangerous when you need to run a dataImport and it overrides the tomcat app deployment whereas it is running.
