### ISSUE TITLE
Tomcat startup error caused by spacing in setenv.sh

### ISSUE THREAD

**Issue by mairi** [Jasig/uPortal-start#229]
**Describe the bug**
When starting tomcat after deploying the bundled tomcat, the following errors appear and tomcat fails to start:

From deployment logs:
<snip>
08-Oct-2018 11:18:58 | [sshexec] /apps/uportal/tomcat/bin/setenv.sh: line 33: [: missing ']'
...
08-Oct-2018 11:18:58 | [sshexec] /apps/uportal/tomcat/bin/setenv.sh: line 39: [: missing ']'
<snip>

It looks like a spacing issue in the setenv.sh file on lines 33 and 39.  I think there should be a space before the ] on those lines.

**To Reproduce**
1. Run the tomcatInstall and tomcatDeploy tasks to build the tomcat artifact in ./gradle/tomcat.
2. Deploy the artifact onto a server.
3. Run startup.sh to start tomcat.
4. Startup fails with the errors noted above.

**Expected behavior**
Tomcat should start without error.

**Stacktrace**
See snip from log output on running startup.sh.

**Platform:**
 - uPortal Version: 5.2.3
 - OS: centos
 - Browser N/A

**Comment by jgribonvald** [comment]
It start because you defined the variable into your environment, or the jvm has default ones

**Comment by mairi** [comment]
Ah yes, that makes sense @jgribonvald thanks
