### ISSUE TITLE
Waffle-menu style problems

### ISSUE THREAD

**Issue by jgribonvald** [Jasig/uPortal-start#263]
**Describe the bug**
Waffle-menu has some style problems

**Screenshots**
see here some screenshots
on chrome when openning the waffle-menu:
![image](https://user-images.githubusercontent.com/1597283/51828754-92adca00-22ec-11e9-9600-c0c7035e351c.png)
 and on firefox developper edition + firefox 64.0.2 when accessing only:
![image](https://user-images.githubusercontent.com/1597283/51828879-d30d4800-22ec-11e9-96ab-b4f3de18b0cf.png)

**Platform:**
 - uPortal Version: 5.4.1
 - OS: ubuntu 18.04
 - Browser: chrome and firefox developper edition + firefox quantum

**Comment by cousquer** [comment]
👋 @jgribonvald in which version is waffle ?

**Comment by jgribonvald** [comment]
@cousquer: nice catch I forgot this point !
I've deployed the lastest version from latest uPortal-start, so the 1.22.1

**Comment by drewwills** [comment]
Folks,

This is absolutely a current issue we have.  I believe @mindblender is working on a fix.
