### ISSUE TITLE
Update uPortal.properties and docs with JWT Sig Alg property

### ISSUE THREAD

**Issue by bjagg** [Jasig/uPortal-start#339]
Add following to etc/portal/uPortal.properties under example signatureKey prop when uPortal is updated to 5.6.1:

```Properties
 
## Signature algorithm option, one of:
##   HS256, HS384, HS512, RS256, RS512, ES256, ES384, ES512, PS256, PS384, PS512
##
## See: https://github.com/jwtk/jjwt/blob/master/api/src/main/java/io/jsonwebtoken/SignatureAlgorithm.java
##
#org.apereo.portal.soffit.jwt.signatureAlgorithm=HS512
```

**Comment by prigaux** [comment]
Great! For RS*, ES* and PS*, we still need a way to separate privateKey from publicKey. Currently there is only signatureKey (which is what HS* needs)!?
