### ISSUE TITLE
Use startStopThreads=0 for tomcat startup

### ISSUE THREAD

**Issue by allanjackson** [Jasig/uPortal-start#365]
The tomcat host startStopThreads setting is currently hard-coded to 4, which is ideal for a 4-core system, but not for any other setup.

Tomcat has a special setting for startStopThreads where if you set it to 0, it will detect how many cores your system has and use that many threads for startup. https://tomcat.apache.org/tomcat-8.5-doc/config/host.html

We should switch the default value of this setting from 4 to 0.

**Comment by ChristianMurphy** [comment]
Thanks for the suggestion @allanjackson! Merged into latest
