### ISSUE TITLE
uPortal fails with Java 8 version above 255

### ISSUE THREAD

**Issue by cbeach47** [Jasig/uPortal-start#468]
**Describe the bug**
Running uP-start with versions of Java 8 greater than 255 fails on login with the error.  Might be uP core's issue.  Will need some investigation.

```
Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
	at com.ibm.icu.util.VersionInfo.getInstance(VersionInfo.java:191)
	at com.ibm.icu.impl.ICUDebug.getInstanceLenient(ICUDebug.java:65)
	at com.ibm.icu.impl.ICUDebug.<clinit>(ICUDebug.java:69)
```

Note:  https://communities.bmc.com/docs/DOC-129065

**To Reproduce**
1. Upgrade Java to 8u265 (I used SDKMan)
2. Start uPortal
3. Access http://localhost:8080/uPortal/Login?userName=admin&password=admin
4. Note error

**Expected behavior**
It should not fail.

**Platform:**
 - uPortal Version: [uPortal 5.8.2]
 - OS: [Ubuntu  16.04]
 - Browser [Firefox]

**Additional context**
Workaround is to downgrade Java8 to something below 255.

**Comment by jgribonvald** [comment]
This problem come from icu4j dependency used in uPortal here:
```

**Comment by nickwoodle** [comment]
Are there any updates on this issue or has it been moved over to uPortal like Julien suggested?

**Comment by jgribonvald** [comment]
doing the change with the forked lib is not difficult, but doing the test is the difficulty for me as I don't know how to use these views quickly. Is there someone who know ?

**Comment by ChristianMurphy** [comment]
Thanks for reporting @cbeach47!
And for tracking down the root cause @jgribonvald!

I've opened two PRs to address this Jasig/uPortal#2157 and #471.
I tested locally with:
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment Corretto-8.265.01.1 (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM Corretto-8.265.01.1 (build 25.265-b01, mixed mode)
```
@jgribonvald @nickwoodle @cbeach47 if you could take it for a test drive and ensure it works in your environment/preferred JDK, it would be appreciated. :bow:
