### ISSUE TITLE
Bundle uPortal-home with uPortal-start

### ISSUE THREAD

**Issue by drewwills** [Jasig/uPortal-start#90]
Also include all required components, as well as ship with a working integration between the two.

**Comment by bjagg** [comment]
Is there still a desire for this feature?

**Comment by ChristianMurphy** [comment]
Interpreting the lack of feedback here as a lack of interest.
Closing this for now.

If interest renews, feel free to comment here and we can reopen the issue.

**Comment by remyjacob** [comment]
I'm interrested in being able to configure uPortal-home with uPortal-start. I've found several bits of configuration docs here and there but as I'm not sure if this is applicable to uPortal-start 5.8.2 and what is really needed to make it work, I'm confused and I would appreciate a detailed step by step guide from start to end.

**Comment by ChristianMurphy** [comment]
Thanks for reaching out @remyjacob 
https://github.com/Jasig/uPortal-start/pull/84 has the most up-to-date, setup/documentation, it's currently stalled due to accessibility issues.
However you're welcome to try it out and offer feedback on it!
