### ISSUE TITLE
Import/Export tasks (dataImport, etc.) are all missing the description field

### ISSUE THREAD

**Issue by drewwills** [Jasig/uPortal-start#98]
None of the Import/Export tasks...

  - `dataDelete`
  - `dataExport`
  - `dataImport`
  - `dataInit`
  - `dataList`

Have a `description` field set, and they should.  It gives us an opportunity to document things like "pass -Dfile={path} to import a file" and so forth.

**Comment by ChristianMurphy** [comment]
Resolved in #157
